---
title: "CCES 2016 question bank"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r input, include =FALSE}
rm(list = ls())

library(DT)
library(dplyr)
library(readr)
library(here)
library(readxl)


# read in question wordings
cq_raw <- readRDS(here("data/output/fmt_metadata_ordered_cc16.Rds"))

sq <- read_excel(here("data/output/meta/Labels_2016.xlsx")) %>% 
  select(Name, Label) %>%
  rename(stataName = Name,
         stataLabel = Label) %>%
  mutate(sOrder = 1:n())



# for DT app
q16.show <- cq_raw %>% 
  arrange(rowID) %>%
  select(alias, name,  wording,labels) %>% 
  rename(`crunch name` = name,
         `choices` = labels,
         `Question wording` = wording) %>%
  mutate(choices = choices)

```

This Table is an informal list of the questions that were asked in the Cooperative Congressional Election Study, Common Content 2016 ([Survey Data on Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GDF6Z0)). 

```{r showDT, echo = FALSE}
datatable(q16.show,
          filter = list(position = 'top', clear = FALSE),
          options = list(searchCols = list(NULL, NULL, NULL, NULL))
)
```

