---
title: "Merge check"
author: "Shiro Kuriwaki"
date: "6/19/2017"
output: html_document
---

```{r, include = FALSE}
library(dplyr)
library(haven)
library(readr)
library(readxl)
library(data.table)
```



# Read 
```{r, message=FALSE}
cq <- readRDS("data/output/meta/fmt_metadata_cc16.Rds") %>%
  mutate(aliasAbbrv = gsub("grid", "", alias))

sq <- read_excel("data/output/meta/Labels_2016.xlsx") %>% 
  select(Name, Label) %>%
  mutate(sOrder = 1:n())

# nathan and liz
nl <- read_csv("data/source/2016_guidebook_variables_orderedby2014.csv")

nl_key <- select(nl, section14, rowID, code14, code16)
```


# Merge Check

Rows in Nathan and Liz's sheet whose `code16` is something that is not in Kattalina's Stata variable list

```{r}
anti_join(nl_key, sq, by = c("code16" = "Name"))
```


Rows in the Kattalina's Stata variable list whose variable code (`Name`) is not in the Nathan and Liz's `code16`.
```{r}
anti_join(sq, nl_key, by = c("Name" = "code16")) %>% 
  arrange(sOrder) %>%
  print(n = 100)
```

